name: Deploy Files to S3

on:
  push:
    branches: 
      - main
    paths:
     - "dev/epicreads_static/**"
  workflow_dispatch:

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ROLE_ARN: ${{ vars.AWS_ROLE_ARN }}

permissions:
  id-token: write
  contents: read 

jobs:
  Deploy:
    name: Deploy Website
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: "dev"
    steps:
      - name: Configure AWS Credentials with Secrets Region
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Upload Files to S3
        run: |
          aws s3 cp ./epicreads_static s3://epic_reads_static_website/ --recursive